[package]
name = "remusys-lang"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22"

[dependencies]
hexf-parse = "0.2.1"
lalrpop-util = { version = "0.22", features = ["lexer"] }
